version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb:custom
    environment:
      MYSQL_DATABASE: wordpress
    secrets:
      - db_user
      - db_password
      - db_root_password
      - credentials
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress:custom
    secrets:
      - db_user
      - db_password
      - credentials
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx:custom
    secrets:
      - credentials
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

secrets:
  db_user:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      device: /home/mayyildi/data/mariadb
      o: 'bind'
      type: 'none'
  wordpress-data:
    driver: local
    driver_opts:
      device: /home/mayyildi/data/wordpress
      o: 'bind'
      type: 'none'

networks:
  inception:
